### PR TITLE
Add FontAwesome Support

### PR DESCRIPTION
**Pull request by johannesschobel**
This PR adds `FontAwesome` support for this package.

# Changes
- Added the `FontAwesome5` fonts (free version!)
- Added a new `glyph($char)` method that correctly transforms a `FontAwesome Unicode` to be used within this package
- Updated the docs

# Why
I recently stumbled across the need to output avatars where the name of the user may be `null` (e.g., it was not set via the "Update Profile" route). Obviously, a simple colored circle was not my first choice, so i thought about printing a "font awesome user icon" instead of the user's initials.

I thought, i will contribute to this awesome package, because YOU saved me with this package a lot (!!!) of work. Giving this back to you is some kind of saying thank you 😆 .

Keep it up - this is a great package!

### CODE REVIEW

**Comment by LasseRafn** [comment]
You rock! Also thanks for the kind words 😄 

I’m on vacation now, but will merge as soon as I’m home 👍  thanks

**Comment by johannesschobel** [comment]
Hey @LasseRafn ,

thank you very much for the fast answer on my PR. I thought this might be quite helpful for one or another ;)

Have a nice vacation and cheers!

**Comment by m1guelpf** [comment]
@johannesschobel Maybe add a test?

**Comment by johannesschobel** [comment]
hey @m1guelpf .. don't think this is necessary, as i only call the `name()` function internally and convert the unicode to a "usable format" for the `OpenTypeFont`...

**Comment by johannesschobel** [comment]
Hey @LasseRafn , sorry to bother you with this PR again.. Did you already find time to review this PR, as the project I am currently developing requires this feature ;)

If you're still on vacation: have fun 😂 haha

**Comment by LasseRafn** [comment]
Haha, thanks 👍 Will fix the travis build bug (not caused by your PR) and eventually also add a test, but for now it seems fine, nothing breaks

**Comment by johannesschobel** [comment]
woooooooooooooooha, thanks for merging ;)

**Pull request merged**
